defaults: &defaults
  fog_provider: 'AWS'
  fog_region:  "<%= ENV['AWS_REGION'] %>"
  aws_access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  aws_secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  # To use AWS reduced redundancy storage.
  # aws_reduced_redundancy: true

  # You may need to specify what region your storage bucket is in
  # fog_region: "eu-west-1"
  existing_remote_files: keep
  # To delete existing remote files.
  existing_remote_files: delete
  # Automatically replace files with their equivalent gzip compressed version
  gzip_compression: true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently: true

development:
  <<: *defaults
  enabled: false

test:
  <<: *defaults
  enabled: false

staging:
  <<: *defaults
  fog_directory: "<%= ENV['AWS_S3_BUCKET_NAME'] %>"

production:
  <<: *defaults
  fog_directory: "<%= ENV['AWS_S3_BUCKET_NAME'] %>"
